### ISSUE TITLE
Rename to address all UN documents as `metanorma-un`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-un#13]
While the models/grammar may be the same, the presentations won't be across UN organizations.

We need to perform some serious analysis (and take up) before we implement 10 different cover pages and intro pages in the same gem with a bunch of conditional logic.

Until that analysis happens, it is premature to rename the gem.

**Comment by ronaldtse** [comment]
Let's move the rename of the gem and its classes forward to accommodate future changes.

**Comment by opoudjis** [comment]
I have done all I need to do, and am releasing the gems tonight. I need one or both of you to update cimas, ci-master and metanorma-build-scripts.

**Comment by ronaldtse** [comment]
Done in https://github.com/metanorma/metanorma-build-scripts/commit/2b5d3023be07035fc06b7a6acd6d0df7d42528d9

**Comment by opoudjis** [comment]
@ronaldtse What remains to be done on thick ticket?

**Comment by ronaldtse** [comment]
@opoudjis nothing. Closing.
