### ISSUE TITLE
lightly not installing right version in 2.7 GHA

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-un#196]
GHA is failing on un-plenary template and un-recommended template because it cannot retrieve the right version of the "lightly" gem.

https://github.com/metanorma/metanorma-un/actions/runs/5304267815/jobs/9600606179?pr=195

`lightly` needs to be 0.3.* for RUBY_VERSION < '3'

lightly is invoked in pubid-iso, pubid-bsi only, with no version number:

`pubid-bsi/pubid-bsi.gemspec:  spec.add_dependency "lightly"`

When the gem is compiled under Ruby 2.7, it retrieves the correct version of lightly; but when run for those two templates, GHA gives the error:

````
ERROR:  Error installing metanorma-cli:
	The last version of lightly (>= 0) to support your Ruby & RubyGems was 0.3.3. Try installing it with `gem install lightly -v 0.3.3` and then running the current command again
	lightly requires Ruby version >= 3.0. The current ruby version is 2.7.8.225.
````

So it is not negotiating lightly down to 0.3.*

@mico would make life easier if his gemspec read:

````
spec.add_dependency "lightly", "~> 0.3.0" if RUBY_VERSION < '3'
spec.add_dependency "lightly", "~> 0.3.0" if RUBY_VERSION >= '3'
````

But @CAMOBAP the latest version of lightly should still be negotiated on metanorma-cli install in Ruby 2.7, shouldn't it?

**Comment by opoudjis** [comment]
Also impacting CSA:

https://github.com/metanorma/metanorma-cc/actions/runs/5303631160/jobs/9599574381?pr=231

**Comment by opoudjis** [comment]
And metanorma-itu:

https://github.com/metanorma/metanorma-itu/actions/runs/5305159597/jobs/9602519685?pr=445

**Comment by CAMOBAP** [comment]
@opoudjis PR https://github.com/metanorma/ci/pull/112 will be merged soon and fix the issue for all repositories

BTW I just trying to understand why this happens at all. Isn't `gem install` smart enough to resolve such cases? AFAIK  `bundle install` can handle such cases without any issues (it cares about Ruby version requirements also)

I have checked the latest versions of lightly https://rubygems.org/gems/lightly/versions/ they declared in metadata ruby requirements...

It's not clear at all why `gem` command asks to do this manual action and not do it itself.

@mico @abunashir maybe you have some thoughts too?

**Comment by opoudjis** [comment]
> BTW I just trying to understand why this happens at all. Isn't `gem install` smart enough to resolve such cases? AFAIK `bundle install` can handle such cases without any issues (it cares about Ruby version requirements also)

It *does* do so on the OSX command line; I suspect this is a GHA issue somehow...

**Comment by abunashir** [comment]
I'm not completely sure why that was happening, but I would suspect as it was not pinning to any relative version, so each implementation was trying to find the best for all other dependencies tree and that might be something was causing in this case.

I think Artur, also removed those dependencies here - https://github.com/metanorma/pubid-iso/pull/232, so are those still relevant and the CI changes as well https://github.com/metanorma/ci/pull/112?
