### ISSUE TITLE
Broken replacement in `#{tc}`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-un#45]
As shown:

ECE_TRADE_C_CEFACT_2018_1E.adoc
https://github.com/metanorma/mn-samples-un/blob/master/sources/ECE_TRADE_C_CEFACT_2018_1E.adoc

```xml
        <title>Note</title>
        <p id="_2240ec44-8f64-4942-a752-43d853c39720">The designations employed and the presentation of the material in this publication do not imply the expression of any opinion whatsoever on the part of the Secretariat of the United Nations concerning the legal status of any country, territory, city or area, or of its authorities, or concerning the delimitation of its frontiers or boundaries.</p>
      </clause>
      <clause>
        <title>#{tc}<br/>Simple, Transparent and Effective Processes for Global Commerce</title>
        <p id="_b35b7b69-9dd3-453e-a9ea-f8d7f7346b2e">UN/CEFACT’s mission is to improve the ability of business, trade and administrative organizations, from developed, developing and transitional economies, to exchange products and relevant services effectively. Its principal focus is on facilitating national and international transactions, through the simplification and harmonization of processes, procedures and information flows, and so contribute to the growth of global commerce.</p>
```

**Comment by ronaldtse** [comment]
This is how it looks when rendered
<img width="829" alt="Screen Shot 2020-03-25 at 5 14 55 PM" src="https://user-images.githubusercontent.com/11865/77520425-290f5880-6ebc-11ea-93c9-02cab5bb4c58.png">

And there is also an HTML tag shown below.

**Comment by w00lf** [comment]
#47

**Comment by opoudjis** [comment]
@w00lf has fixed.

**Comment by manuel489** [comment]
Hi @w00lf, I have confirmed that `#{tc}` issue is fixed. However, I think that the HTML tag issue persists, according to my outputs. (I have fetched directly from *metanorma-un* repo.)

![Capture2](https://user-images.githubusercontent.com/33627611/80640282-2e1e7500-8a31-11ea-9ad9-ce68cf531db0.PNG)

My outputs: 
[Rec42.zip](https://github.com/metanorma/metanorma-un/files/4554207/Rec42.zip)
