### ISSUE TITLE
`recommendation` doctype sidebar color missing

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-un#46]
Notice that the recommendation doctype is not showing due to the missing color:

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/11865/77520772-a935be00-6ebc-11ea-8c0c-7c9be9ef95de.png">

**Comment by w00lf** [comment]
Fixed in #47

**Comment by opoudjis** [comment]
Also fixed in https://github.com/metanorma/metanorma-ogc/issues/107 : if no band colour specified, default now is black (to deal with white lettering).
