### ISSUE TITLE
Title provided but not set in XML

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-un#49]
Title is not set in XML for:
https://metanorma.github.io/mn-samples-un/documents/ECE_TRADE_437E_Rec42.html

https://github.com/metanorma/mn-samples-un/blob/master/sources/ECE_TRADE_437E_Rec42.adoc

But the source clearly had a title.
```
= Trade and Transport Facilitation Monitoring Mechanism
:doctype: recommendation
:docnumber: 42
:status: published
:committee: United Nations Centre for Trade Facilitation and Electronic Business (UN/CEFACT)
...
```

**Comment by ronaldtse** [comment]
This one as well:

https://github.com/metanorma/mn-samples-un/blob/master/sources/ECE_TRADE_C_CEFACT_2019_26.adoc

```adoc
= Briefing note on sustainable textile value chains in the garment and footwear domain for SDG12
:doctype: plenary
:docnumber: GE.19-04574(E)
:committee: United Nations Centre for Trade Facilitation and Electronic Business (UN/CEFACT)
:status: published
```

**Comment by ronaldtse** [comment]
In fact, the generated output is like this:

```xml
<bibdata type="standard">

<title type="subtitle" language="en" format="text/plain">How Does It Impact the Trade System?</title>
<docidentifier>GE.18-02016(E)</docidentifier>
```

Only the subtitle is set; title is lost.

**Comment by opoudjis** [comment]
This has in fact been fixed in https://github.com/metanorma/metanorma-un/commit/4531fccc7d8945394dfe7476c089f25288b5cb1d, in response to https://github.com/metanorma/mn-native-pdf/issues/90
