### ISSUE TITLE
Provide proper UN location

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-un#50]
Now:

```xml
<organization>
<name>United Nations</name>
<abbreviation>UN</abbreviation>
</organization>
```

**Comment by opoudjis** [comment]
... What do you mean?

**Comment by ronaldtse** [comment]
Sorry for being brief; I meant to provide an address but the author should be able to specify the "publisher".

In the case of UNECE REC 42, it is this:

<img width="265" alt="Screen Shot 2020-04-01 at 7 32 15 PM" src="https://user-images.githubusercontent.com/11865/78132546-80c73a00-744f-11ea-9d46-e019c2ae259b.png">

All the mn-sample-un documents right now are UNECE documents, as can be seen in the headers:
<img width="542" alt="Screen Shot 2020-04-01 at 7 33 31 PM" src="https://user-images.githubusercontent.com/11865/78132635-ace2bb00-744f-11ea-9f64-44a2b753b705.png">

**Comment by ronaldtse** [comment]
Information Service
United Nations Economic Commission for Europe
Palais des Nations
CH - 1211 Geneva 10
Switzerland

Telephone: +41(0)22 917 44 44
Fax: +41(0)22 917 05 05
E-mail: info.ece@unece.org
Website: http://www.unece.org

**Comment by opoudjis** [comment]
Not just a publisher, but an address as well. And given the formatting of the address, it is inanity to implement the address as a parameter, and I will not do it.

The publisher will be specified somewhere as a parameter, and the corresponding template and/or formatted address will be looked up. 

And as to what those addresses or templates will be other than UNECE: get back to me when you have someone using this other than UNECE. This is farcically premature.

**Comment by opoudjis** [comment]
Addressed in https://github.com/metanorma/metanorma-un/issues/61
