### ISSUE TITLE
Blank page appears when footnote is present in front page

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-un#53]
When a footnote is placed in the front page (e.g. in the Summary), a blank page is introduced between the front page and the main content.

For demonstration, please checkout the file:
[ECE_TRADE_C_CEFACT_2019_22_REV1.zip](https://github.com/metanorma/metanorma-un/files/4506951/ECE_TRADE_C_CEFACT_2019_22_REV1.zip)

In addition to that problem, even if there no is blank page, if I place the cursor on the second page the Word page indicator (at the bottom left corner) says that I am on the third one 😕.

**Comment by opoudjis** [comment]
The blank page is a very simple issue: the plenary cover page in Word has a whole lot of empty paragraphs, to put the session id vaguely at the bottom of the page; if the abstract is any longer than expected, or if a footnote shows up, the page overflows into the next page.

The only thing to do here is to put the session id in a text box, which will be statically at the bottom of the page. And hope that the text box doesn't clash with any footnotes.
