### ISSUE TITLE
Format issues in Plenary template

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-un#59]
From doc: https://github.com/metanorma/mn-samples-un/blob/master/sources/ECE_TRADE_C_CEFACT_2018_6E.adoc

- Paragraphs are not getting numbered

*Original:*
![issue1-original](https://user-images.githubusercontent.com/33627611/80644178-3da0bc80-8a37-11ea-95e4-813e23c4816f.PNG)

*Generated:*
![issue1-generated](https://user-images.githubusercontent.com/33627611/80644197-442f3400-8a37-11ea-9473-f45e42753919.PNG)

- Sub-clause numbering starts from "2"

*Original:*
![issue2-original](https://user-images.githubusercontent.com/33627611/80644210-485b5180-8a37-11ea-889d-3c882ee3dbce.PNG)

*Generated:*
![issue2-generated](https://user-images.githubusercontent.com/33627611/80644219-4b564200-8a37-11ea-9403-2ec1ac2fca75.PNG)

- Wrong clause numbering. Clauses are getting numbered as if they were sub-clauses. (The first Clause gets numbered correctly.)

*Original:*
![issue3-original](https://user-images.githubusercontent.com/33627611/80644343-80629480-8a37-11ea-80fe-8999876dfb82.PNG)

*Code:*
````
== Paperless Trade Challenges
Paperless trade is not without challenges. The set-up and operation of paperless trade measures, 
supporting regulation and electronic single windows, is not yet a given across all countries. The UN
 has conducted a survey of 120 countries, across a range of 38 measures related to trade facilitation 
and paperless trading. 
````

*Generated:*
![issue3-generated](https://user-images.githubusercontent.com/33627611/80644351-82c4ee80-8a37-11ea-9fbe-e6d9d9084467.PNG)

- Admonitions numbering starts from "0"

*Original:*
![issue4-original](https://user-images.githubusercontent.com/33627611/80644373-89ebfc80-8a37-11ea-989f-d34a94bd63de.PNG)

*Generated:*
![issue4-generated](https://user-images.githubusercontent.com/33627611/80644377-8c4e5680-8a37-11ea-9ac8-aa3f5225273d.PNG)

**Comment by opoudjis** [comment]
> Paragraphs are not getting numbered

The current rule is, paragraphs are numbered except when the document is one of: plenary agenda budgetary.

At issue here is: this document is NOT in fact a plenary document (which would be an agenda); it is an *attachment* to an agenda. Its doctype, therefore, is `plenary-attachment`. Fixing.

**Comment by opoudjis** [comment]
Now, Benefits for Traders does have a subheading number, A. There is no provision in code for there to be no numbering for a subheading, even if the paragraph numbering arguably makes it redundant. This should be escalated to UN before changing anything; unnumbered floating headings are bad practice regardless.

**Comment by opoudjis** [comment]
Box 0 issue fixed.

**Comment by opoudjis** [comment]
Damn:

http://dd.dgacm.org/editorialmanual/ed-guidelines/format/headings.htm

> Chapter or main section headings are identified by roman numerals and first-degree subheadings by capital letters. In reports with a limited number of subsections, subheadings may be used without identifying numbers or letters.

Ugh. Ok, we will have to introduce the unnumbered attribute to UN documents, applied to subclauses. So,

````
[unnumbered="true"]
=== Benefits for Traders
````

... Yuck.
