### ISSUE TITLE
Format discrepancies in Recommendation template respect to original source

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-un#61]
*This issue is related to* https://github.com/metanorma/mn-native-pdf/issues/151 and https://github.com/metanorma/mn-native-pdf/issues/61

This ticket report two format discrepancies I've noticed in UN Recomendation template. 

- In XML, the organization's name is "United Nations", while in original source is "UNECE"

*Generated XML:*
````
<?xml version="1.0" encoding="UTF-8"?>
<un-standard xmlns="https://www.metanorma.org/ns/un">
<bibdata type="standard">
<title type="main" language="en" format="text/plain">Trade and Transport Facilitation Monitoring Mechanism</title>
<docidentifier>42</docidentifier>
<docnumber>42</docnumber>
<contributor>
<role type="author"/>
<organization>
<name>United Nations</name>
<abbreviation>UN</abbreviation>
</organization>
</contributor>
<contributor>
<role type="publisher"/>
<organization>
<name>United Nations</name>
<abbreviation>UN</abbreviation>
</organization>
</contributor>
````

*Original source:*
![img1](https://user-images.githubusercontent.com/33627611/80896197-fd04a580-8cb9-11ea-91c3-9ecbcecb408a.png)

- In XML, the information contact differs, e.g., the fax number is missing, the email address is different, the "https://" of the website link is missing, etc.

*Generated XML:*
````
  <feedback-statement>
    <clause>
      <p id="boilerplate-feedback-name">UN Economic Commission for Europe: Information Service</p>
      <p id="boilerplate-feedback-address">
        Palais des Nations<br/>
        CH-1211 Geneva 10<br/>
        Switzerland<br/>
        <br/>
        <link target="tel:+41(0)229171234">+41 (0) 22 917 12 34 (switchboard)</link><br/>
        <link target="mailto:unece_info@un.org">unece_info@un.org</link><br/>
        <link target="https://www.unece.org/">www.unece.org/</link>
      </p>
    </clause>
  </feedback-statement>
````

*Original source:*
![cap4-original](https://user-images.githubusercontent.com/33627611/80598221-05798980-89f7-11ea-93a5-f70df5561837.PNG)

Thanks!

**Comment by ronaldtse** [comment]
Thanks @manuel489 for raising this! This is a real issue indeed, we need to either have a way to encode them properly in the gem (probably using YAML).

**Comment by opoudjis** [comment]
For the first issue:

The organisation is the UN, now that the gem has become generically a gem for the UN; but UNECE does need to be added to the metadata of the document, as an organisation subdivision.

**Comment by opoudjis** [comment]
`:address:`, `:contributor-uri:`, `:email:`, `:phone:`, `:fax:` are already defined for personal authors. We can define a contact set of these as well, which would then override the default in the boilerplate if provided.

**Comment by opoudjis** [comment]
Have defined document attributes for all of these: `:pub-address` (which needs to use ` + \ ` for line breaks), `:pub-fax:`, `:pub-phone:`, `:pub-email:`, `:pub-uri:`. I am allowing these to override the default in the UN boilerplate.
