### ISSUE TITLE
Footnotes on main title

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-un#77]
Follow-on from #54:

I have just introduced a notation for footnotes on the main title:

* Each footnote to be added to the main title is an entry in `/bibdata/note[@type = 'title-footnote']`
* Each such footnote is to be indicated with asterisks: `*`, `**`, `***` etc
* Title page footnotes are be displayed after the main title

So:

____
Title `*,**,***`

 `*` xxx
 `**` xxxx
 `***` xxxx
____

**Comment by Intelligent2013** [comment]
Done:
![изображение](https://user-images.githubusercontent.com/5559926/97978208-4c996a80-1dde-11eb-8048-3aac413ae2fe.png)
